package com.bot.dhxy.cloud.remote;

import com.bot.dhxy.config.BotProperties;
import com.bot.dhxy.core.ImageFinder;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

/**
 * W-TEAMRETURN-MECH-LEAF-IMP1 (CR TeamReturnService lift-and-shift): the local-mechanics owner of the
 * leader-signal precheck. It holds the single {@link LeaderPrecheckFrameRegistry}, runs the {@code
 * zhao.png} template match at the baseline match rate over the frame the bound capability captured, and
 * orchestrates the registry lifecycle. The exact-window ROI is generated by the handler-bound capability
 * (from the verified binding), so the mechanics no longer reads {@code CoordinateHelper}/tracker; it
 * keeps {@link BotProperties} only for the analysis match rate. It exposes only three typed domain
 * operations; the seven registry primitives, the raw registry, the templates, and the coordinates never
 * leak to Cloud business.
 *
 * <p>This is an <em>unmounted, dormant</em> leaf: no one constructs or drives it in this wave. The
 * capture authority is supplied per command by a {@link BoundLeaderPrecheckCaptureCapability} that the
 * frozen {@code LocalRemoteGameCommandHandler} mints after its binding+registration gate (owner gate
 * M2); terminal release is driven by {@code RemoteTaskRunLifecycleService.consumeTerminal} (owner gate
 * M1). Both wirings stay frozen here.</p>
 *
 * <p>Encoding order (Parent Design Review #14/#16): {@code reserve} borrows the admission permit before
 * any {@link BufferedImage} exists; only a {@code FRESH} reservation captures; a null frame settles via
 * {@code captureFailed}; a lost attach flushes then cancels; the analysis is submitted once via HEAD's
 * default {@link CompletableFuture#supplyAsync} facility and its future is bound only as a cancellation
 * aid. Every typed analysis outcome (including a failure reason) settles through {@code completeSuccess};
 * only a value-less worker failure would use {@code completeFailed}.</p>
 */
final class LeaderPrecheckMechanics {

    private static final String LEADER_RETURN_SIGNAL_PATH = "images/template/status/zhao.png";

    private final LeaderPrecheckFrameRegistry<LeaderSignalPrecheckResult> registry;
    private final BotProperties botProperties;

    LeaderPrecheckMechanics(int globalFrameLimit, BotProperties botProperties) {
        this.registry = new LeaderPrecheckFrameRegistry<>(globalFrameLimit);
        this.botProperties = botProperties;
    }

    /**
     * Domain op 1: begin a leader-precheck. Reserves first (permit fence), captures only when FRESH via
     * the supplied bound capture, attaches the single frame, and submits the analysis exactly once.
     */
    LeaderPrecheckHandle beginLeaderPrecheck(RemoteClientSessionRef session,
                                             String taskRunId,
                                             String windowId,
                                             String source,
                                             BoundLeaderPrecheckCaptureCapability capture) {
        LeaderPrecheckFrameRegistry.Reservation<LeaderSignalPrecheckResult> reservation =
                registry.reserve(session, taskRunId, windowId);
        switch (reservation.status()) {
            case FRESH -> {
                // proceed below
            }
            case REUSED_ACTIVE -> {
                return LeaderPrecheckHandle.settled(LeaderSignalPrecheckStatus.inconclusive("reused-active"));
            }
            case TEARDOWN_BUSY -> {
                return LeaderPrecheckHandle.settled(LeaderSignalPrecheckStatus.inconclusive("teardown-busy"));
            }
            case CAPACITY_REJECTED -> {
                return LeaderPrecheckHandle.settled(LeaderSignalPrecheckStatus.inconclusive("capacity-rejected"));
            }
        }

        // FRESH: any exception on capture/attach must give the borrowed permit total cleanup — a
        // no-frame path releases via captureFailed, a captured-but-unattached frame is flushed then
        // cancel'd — before the exception propagates. Never swallow a stop/Error into NO_SIGNAL. The
        // capability owns ROI generation from the verified binding, so no rect is passed in.
        BoundLeaderPrecheckCaptureCapability.CaptureAttempt attempt;
        BufferedImage frame = null;
        boolean attached = false;
        try {
            attempt = capture.capture();
            frame = attempt.frame();
            if (frame == null) {
                registry.captureFailed(reservation);
                String reason = attempt.failureReason() == null ? "capture-failed" : attempt.failureReason();
                return LeaderPrecheckHandle.settled(LeaderSignalPrecheckStatus.inconclusive(reason));
            }
            attached = registry.attachFrame(reservation, frame);
        } catch (RuntimeException | Error failure) {
            if (frame != null && !attached) {
                frame.flush();
                registry.cancel(reservation);
            } else if (!attached) {
                registry.captureFailed(reservation);
            }
            throw failure;
        }
        if (!attached) {
            frame.flush();
            registry.cancel(reservation);
            return LeaderPrecheckHandle.settled(LeaderSignalPrecheckStatus.inconclusive("attach-failed"));
        }

        // frame ownership has transferred to the registry; it is the sole flush/release owner from here.
        // The absolute hit reuses the exact corner origin the capability cropped from (x1, y1).
        final int rectX = attempt.x1();
        final int rectY = attempt.y1();
        CompletableFuture<LeaderSignalPrecheckResult> future;
        try {
            future = CompletableFuture.supplyAsync(() -> analyzeAndSettle(reservation, rectX, rectY, source));
        } catch (RuntimeException submitFailure) {
            registry.submitRejected(reservation);
            return LeaderPrecheckHandle.settled(LeaderSignalPrecheckStatus.inconclusive("submit-rejected"));
        }
        registry.bindFuture(reservation, future);
        return LeaderPrecheckHandle.live(reservation);
    }

    /** Domain op 2: poll the exact handle for a typed status without exposing the registry or frame. */
    LeaderSignalPrecheckStatus pollLeaderPrecheck(LeaderPrecheckHandle handle) {
        LeaderSignalPrecheckStatus settled = handle.settledStatus();
        if (settled != null) {
            return settled;
        }
        LeaderPrecheckFrameRegistry.ConsumeResult<LeaderSignalPrecheckResult> consumed =
                registry.consume(handle.reservation());
        switch (consumed.status()) {
            case READY -> {
                LeaderSignalPrecheckResult result = consumed.value();
                return switch (result.status()) {
                    case SIGNAL_PRESENT -> LeaderSignalPrecheckStatus.withSignal();
                    case NO_SIGNAL -> LeaderSignalPrecheckStatus.noSignal();
                    case FAILED -> LeaderSignalPrecheckStatus.inconclusive(result.reason());
                };
            }
            case NOT_READY -> {
                return LeaderSignalPrecheckStatus.inconclusive("not-ready");
            }
            case FAILED -> {
                return LeaderSignalPrecheckStatus.inconclusive("failed");
            }
            case STALE -> {
                return LeaderSignalPrecheckStatus.inconclusive("stale");
            }
        }
        return LeaderSignalPrecheckStatus.inconclusive("unknown");
    }

    /** Domain op 3: owner terminal cleanup for one exact run/window (idempotent, keyed only). */
    void releaseTerminal(RemoteClientSessionRef session, String taskRunId, String windowId) {
        registry.releaseRun(session, taskRunId, windowId);
    }

    /**
     * Analysis worker: byte-faithful migration of HEAD {@code analyzeLeaderSignalSnapshot}. Reads the
     * frame only after a successful {@link LeaderPrecheckFrameRegistry#pickup}; a lost pickup reads,
     * flushes, and settles nothing. An analysis {@link Exception} forms a typed FAILED result and settles
     * via {@code completeSuccess}; a value-less throwable ({@link Error}) that escapes settles once via
     * {@code completeFailed} in the {@code finally} and then propagates, so a picked-up slot never stays
     * {@code IN_FLIGHT} with its frame and permit leaked.
     */
    private LeaderSignalPrecheckResult analyzeAndSettle(
            LeaderPrecheckFrameRegistry.Reservation<LeaderSignalPrecheckResult> reservation,
            int rectX,
            int rectY,
            String source) {
        BufferedImage frame = registry.pickup(reservation);
        if (frame == null) {
            return null;
        }
        boolean settled = false;
        try {
            LeaderSignalPrecheckResult result;
            try {
                BufferedImage template = ImageIO.read(Path.of(LEADER_RETURN_SIGNAL_PATH).toFile());
                double[] match = ImageFinder.find(frame, template, botProperties.getReturnTeamMatchRate());
                if (match == null || match.length < 2) {
                    result = LeaderSignalPrecheckResult.noSignal();
                } else {
                    int absoluteX = rectX + (int) Math.round(match[0]);
                    int absoluteY = rectY + (int) Math.round(match[1]);
                    result = LeaderSignalPrecheckResult.signalPresent(absoluteX, absoluteY);
                }
            } catch (Exception e) {
                result = LeaderSignalPrecheckResult.failed(e.getClass().getSimpleName());
            }
            registry.completeSuccess(reservation, result);
            settled = true;
            return result;
        } finally {
            if (!settled) {
                registry.completeFailed(reservation);
            }
        }
    }

    /**
     * Opaque closed handle returned by {@link #beginLeaderPrecheck}. A {@code Live} handle carries the
     * exact opaque reservation for a later {@link #pollLeaderPrecheck}; a {@code Settled} handle carries a
     * pre-computed terminal status for an immediate capture/attach/submit failure or a non-FRESH
     * admission. It carries no second frame/registry ledger.
     */
    static final class LeaderPrecheckHandle {

        private final LeaderPrecheckFrameRegistry.Reservation<LeaderSignalPrecheckResult> reservation;
        private final LeaderSignalPrecheckStatus settledStatus;

        private LeaderPrecheckHandle(
                LeaderPrecheckFrameRegistry.Reservation<LeaderSignalPrecheckResult> reservation,
                LeaderSignalPrecheckStatus settledStatus) {
            this.reservation = reservation;
            this.settledStatus = settledStatus;
        }

        static LeaderPrecheckHandle live(
                LeaderPrecheckFrameRegistry.Reservation<LeaderSignalPrecheckResult> reservation) {
            return new LeaderPrecheckHandle(reservation, null);
        }

        static LeaderPrecheckHandle settled(LeaderSignalPrecheckStatus settledStatus) {
            return new LeaderPrecheckHandle(null, settledStatus);
        }

        LeaderPrecheckFrameRegistry.Reservation<LeaderSignalPrecheckResult> reservation() {
            return reservation;
        }

        LeaderSignalPrecheckStatus settledStatus() {
            return settledStatus;
        }
    }
}
