package com.bot.dhxy.cloud.remote;

public enum RemoteGameOperation {
    CAPTURE,
    WINDOW_FACT,
    EXECUTE_INPUT_BUNDLE,
    EXCLUSIVE_INTERACTION_CONTROL,
    SUMMON_SKILL_WHOLE_PASS,
    TASK_TRACKER_READ,
    TASK_TRACKER_MATERIALIZE_ACTION,
    LOCAL_MACRO
}
