package com.bot.dhxy.cloud.remote;

public enum RemoteOutcomeCode {
    OK,
    FINAL_CONSUMED,
    INVALID_REQUEST,
    AUTH_FAILED,
    IDEMPOTENCY_CONFLICT,
    ACTION_ID_REUSE,
    WRONG_WINDOW,
    WINDOW_BINDING_CHANGED,
    TASK_RUN_MISMATCH,
    TASK_RUN_PAUSED,
    STOP_REQUESTED,
    BROKER_CAPACITY_EXCEEDED,
    TIMEOUT,
    CAPTURE_FAILED,
    FACT_UNAVAILABLE,
    INPUT_QUEUE_REJECTED,
    INPUT_FAILED,
    TRANSPORT_LOST,
    CLIENT_RESTARTED,
    INTERNAL_ERROR
}
