package com.bot.dhxy.cloud.remote;

public enum RemoteTaskRunErrorCode {
    INVALID_REQUEST,
    NOT_FOUND,
    CONFLICT,
    SESSION_CONFLICT,
    RECONCILE_REQUIRED,
    STALE_REVISION,
    FUTURE_REVISION,
    BINDING_MISMATCH,
    REGISTRATION_MISMATCH,
    LOCAL_NOT_QUIESCENT,
    RECONCILE_NOT_EXPECTED,
    IDEMPOTENCY_CONFLICT,
    TERMINAL,
    CAPACITY_EXCEEDED,
    INTERNAL_ERROR
}
