package com.bot.dhxy.cloud.remote;

public enum RemoteWindowFactKind {
    BINDING,
    GEOMETRY,
    FOCUS_STATE,
    STOP_STATE,
    LEFT_TOP_STATUS,
    AUTO_COMBAT_PANEL,
    COMMON_BOX,
    TEAM_RETURN_BUTTON,
    TEAM_RETURN_LEADER_SIGNAL,
    TASK_TRACKER_PANEL_RECT,
    BATTLE_RADAR_AUTO_FLAG,
    BATTLE_RADAR_SELECTION_SIGNAL,
    BATTLE_RADAR_TOP_SIGNAL,
    BATTLE_RADAR_MINIMAP_READABLE,
    BATTLE_RADAR_AVATAR_BASELINE,
    BATTLE_RADAR_AVATAR_PROBE,
    BATTLE_RADAR_AVATAR_REFRESH
}
