package com.bot.dhxy.cloud.remote;

public enum RemoteInputActionType {
    CLICK_LEFT,
    CLICK_RIGHT,
    DOUBLE_RIGHT_CLICK,
    MOVE_MOUSE,
    DRAG_AND_DROP,
    HOLD_CTRL,
    RELEASE_CTRL,
    PRESS_CTRL_U,
    TYPE_TEXT_UNICODE,
    PASTE_TEXT,
    PRESS_ENTER,
    PRESS_ALT_1,
    PRESS_ALT_2,
    PRESS_ALT_4,
    PRESS_ALT_6,
    PRESS_ALT_8,
    PRESS_ALT_T,
    PRESS_ALT_O,
    PRESS_ALT_E,
    PRESS_ALT_Q,
    PRESS_ALT_A,
    PRESS_ALT_C,
    PRESS_ALT_U,
    SCROLL_DOWN,
    SCROLL_UP,
    SLEEP
}
