package com.bot.dhxy.cloud.task;

public enum ImagePreprocessOperation {
    WASH_YELLOW,
    WASH_GREEN,
    WASH_WHITE,
    WASH_PURPLE,
    WASH_DIALOG_OPTION_TEMPLATE,
    WASH_AUTO_COMBAT_ROUND_RED_DIGITS,
    ROUTE_PACKED_LINE_MASK,
    ROUTE_DESTINATION_SEGMENTS,
    FINGERPRINT,
    TEXT_CANDIDATES,
    COUNT_YELLOW_PIXELS,
    COUNT_GREEN_PIXELS_HSV,
    COUNT_THIN_WHITE_PIXELS_HSV,
    FIND_GREEN_TEXT_BANDS,
    PICK_GREEN_TEXT_BAND,
    BUILD_BINARY_FINGERPRINT,
    BINARY_FINGERPRINT_DISTANCE,
    DETECT_THIN_WHITE_TEXT_LINE_PATTERN,
    MEASURE_STDDEV,
    MEASURE_TEAM_TOOLTIP_TEXT
}
