package com.bot.dhxy.model.dialog;

/**
 * Stable status returned by scoped dialog handling.
 */
public enum DialogResultStatus {
    NO_DIALOG,
    STORY_IGNORED,
    STORY_CLICKED,
    STORY_OBJECTIVE_READ,
    STORY_OBJECTIVE_NOT_FOUND,
    OPTION_IGNORED,
    OPTION_VISIBLE,
    OPTION_KEYWORD_CLICKED,
    OPTION_KEYWORD_NOT_FOUND,
    BUSINESS_OPTION_CLICKED,
    BUSINESS_OPTION_NOT_FOUND,
    GIVE_ITEM_DONE,
    GIVE_OPTION_NOT_FOUND,
    GIVE_ITEM_FAILED,
    GREEN_TEMPLATE_CLICKED,
    GREEN_TEMPLATE_VISIBLE,
    GREEN_TEMPLATE_NOT_FOUND,
    WHITE_TEMPLATE_VISIBLE,
    WHITE_TEMPLATE_NOT_FOUND,
    FALLBACK_CLICKED,
    DIALOG_PREPARING,
    INTERRUPTED,
    FAILED
}
