package com.bot.dhxy.cloud.turn.local;

import com.bot.dhxy.driver.BoundWindowCaptureService;
import com.bot.dhxy.input.InputProvider;
import com.bot.dhxy.input.InputSequences;
import com.bot.dhxy.window.model.WindowNativeBinding;
import com.bot.dhxy.window.runtime.WindowNativeBindingRefreshService;
import com.bot.dhxy.window.runtime.WindowRuntimeContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.nio.ByteBuffer;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.BooleanSupplier;

/**
 * Local mechanical half of the CR212 repaired team-role preflight.
 *
 * <p>For one selected start batch this service first groups exact HWND captures at the tooltip hover anchor,
 * without physical input. It then serializes hover/capture only for one usable representative per group and
 * removes that tooltip background. It intentionally does not OCR or decide leader/member: Cloud receives one
 * representative mask per group and compares its OCR leader ID with every window title. No task phase,
 * navigation, or maintenance decision is owned here.</p>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class LocalTeamRolePreflightService {

    private static final int HOVER_X = 644;
    private static final int HOVER_Y = 91;
    private static final int HOVER_RADIUS_X = 8;
    private static final int HOVER_RADIUS_Y = 6;
    private static final int TEAM_ANCHOR_SIZE = 10;
    private static final int TOOLTIP_X = 680;
    private static final int TOOLTIP_Y = 124;
    private static final int TOOLTIP_W = 111;
    private static final int TOOLTIP_H = 84;
    private static final int TOOLTIP_ATTEMPTS = 2;
    private static final long HOVER_SETTLE_MS = 500L;
    private static final long RETRY_WAIT_MS = 1_000L;
    private static final int WHITE_MIN = 100;
    private static final int PURPLE_MIN = 20;

    private final InputSequences inputSequences;
    private final InputProvider inputProvider;
    private final BoundWindowCaptureService captureService;
    private final WindowNativeBindingRefreshService bindingRefreshService;

    /**
     * Produce one immutable local preflight fact for every selected window.
     *
     * @param contexts exact selected runtime contexts; each must have a live native binding
     * @param localTeamSessionKey nonblank batch-local grouping key generated by the start owner
     * @return window-id keyed facts; a tooltip group has exactly one representative mask payload
     */
    public Map<String, Preflight> prepareBatch(List<WindowRuntimeContext> contexts, String localTeamSessionKey) {
        return prepareBatch(contexts, localTeamSessionKey, () -> false);
    }

    /**
     * Produce one preflight batch that stops issuing physical input as soon as its start owner is cancelled.
     *
     * @param contexts exact selected runtime contexts
     * @param localTeamSessionKey nonblank batch-local grouping key
     * @param cancelled true after pause/stop invalidates this start command
     * @return completed facts gathered before cancellation; callers must reject a cancelled batch
     */
    public Map<String, Preflight> prepareBatch(
            List<WindowRuntimeContext> contexts,
            String localTeamSessionKey,
            BooleanSupplier cancelled) {
        if (contexts == null || contexts.isEmpty()) {
            return Map.of();
        }
        if (localTeamSessionKey == null || localTeamSessionKey.isBlank()) {
            throw new IllegalArgumentException("localTeamSessionKey is required");
        }
        BooleanSupplier cancellation = java.util.Objects.requireNonNull(cancelled, "cancelled");
        Map<String, Candidate> candidates = new LinkedHashMap<>();
        for (WindowRuntimeContext context : contexts.stream()
                .filter(java.util.Objects::nonNull)
                .sorted(Comparator.comparing(WindowRuntimeContext::getWindowId))
                .toList()) {
            if (cancellation.getAsBoolean()) {
                break;
            }
            candidates.put(context.getWindowId(), Candidate.of(context, captureAnchorHash(context, cancellation)));
        }

        Map<String, List<Candidate>> byAnchor = new LinkedHashMap<>();
        for (Candidate candidate : candidates.values()) {
            if (candidate.anchorHash != null) {
                byAnchor.computeIfAbsent(candidate.anchorHash, ignored -> new ArrayList<>()).add(candidate);
            }
        }
        Map<String, Preflight> results = new LinkedHashMap<>();
        for (Candidate candidate : candidates.values()) {
            if (candidate.anchorHash == null) {
                results.put(candidate.windowId, Preflight.completed(candidate.windowId, Role.UNKNOWN, null, false, null));
            }
        }
        for (Map.Entry<String, List<Candidate>> entry : byAnchor.entrySet()) {
            String groupHash = "anchor-" + entry.getKey();
            List<Candidate> group = entry.getValue();
            TooltipResolution resolution = resolveTooltipRepresentative(group, cancellation);
            TooltipCandidate representative = resolution.representative();
            if (representative == null) {
                for (Candidate candidate : group) {
                    Role role = resolution.captureSucceeded() && candidate.context.getSelectedTaskType().isSinglePlayer()
                            ? Role.SOLO
                            : Role.UNKNOWN;
                    results.put(candidate.windowId, Preflight.completed(candidate.windowId, role, null, false, null));
                }
                log.info("local team-role anchor group has no usable tooltip: session={} groupHash={} groupSize={} "
                                + "captureSucceeded={} soloTasks={}",
                        localTeamSessionKey, groupHash, group.size(), resolution.captureSucceeded(),
                        group.stream().filter(candidate -> candidate.context.getSelectedTaskType().isSinglePlayer()).count());
                continue;
            }
            for (Candidate candidate : group) {
                boolean isRepresentative = representative.candidate == candidate;
                results.put(candidate.windowId, Preflight.completed(
                        candidate.windowId,
                        Role.UNKNOWN,
                        groupHash,
                        isRepresentative,
                        isRepresentative ? representative.payload.base64() : null));
                log.info("local team-role anchor group: session={} groupHash={} windowId={} representative={} groupSize={}",
                        localTeamSessionKey, groupHash, candidate.windowId, isRepresentative, group.size());
            }
        }
        return Map.copyOf(results);
    }

    private TooltipResolution resolveTooltipRepresentative(List<Candidate> group, BooleanSupplier cancelled) {
        boolean captureSucceeded = false;
        for (Candidate candidate : group) {
            TooltipInspection inspection = inspectTooltip(candidate.context, cancelled);
            captureSucceeded |= inspection.captureSucceeded();
            if (inspection.payload() != null) {
                return new TooltipResolution(
                        new TooltipCandidate(candidate, inspection.payload()),
                        true);
            }
            if (cancelled.getAsBoolean()) {
                return new TooltipResolution(null, captureSucceeded);
            }
            log.info("local team-role tooltip representative retrying next same-anchor window: windowId={} groupSize={}",
                    candidate.windowId, group.size());
        }
        return new TooltipResolution(null, captureSucceeded);
    }

    private TooltipInspection inspectTooltip(WindowRuntimeContext context, BooleanSupplier cancelled) {
        boolean captureSucceeded = false;
        for (int attempt = 1; attempt <= TOOLTIP_ATTEMPTS; attempt++) {
            if (cancelled.getAsBoolean()) {
                return new TooltipInspection(null, captureSucceeded);
            }
            BufferedImage tooltip = hoverAndCapture(context, cancelled);
            if (tooltip != null) {
                captureSucceeded = true;
                try {
                    if (looksLikeTooltip(tooltip)) {
                        MaskPayload payload = mask(tooltip);
                        if (payload != null) {
                            persistTooltipEvidence(context.getWindowId(), tooltip, payload);
                            return new TooltipInspection(payload, true);
                        }
                    }
                } finally {
                    tooltip.flush();
                }
            }
            if (attempt < TOOLTIP_ATTEMPTS && !sleep(RETRY_WAIT_MS, cancelled)) {
                return new TooltipInspection(null, captureSucceeded);
            }
        }
        return new TooltipInspection(null, captureSucceeded);
    }

    private String captureAnchorHash(WindowRuntimeContext context, BooleanSupplier cancelled) {
        if (cancelled.getAsBoolean()) {
            return null;
        }
        WindowNativeBinding binding = bindingRefreshService.refreshAndCommit(context).orElse(null);
        BufferedImage anchor = binding == null ? null : capture(binding, HOVER_X, HOVER_Y, TEAM_ANCHOR_SIZE, TEAM_ANCHOR_SIZE);
        if (anchor == null) {
            log.warn("local team-role anchor capture failed: windowId={}", context.getWindowId());
            return null;
        }
        try {
            return rawArgbSha256(anchor);
        } finally {
            anchor.flush();
        }
    }

    private void persistTooltipEvidence(String windowId, BufferedImage raw, MaskPayload payload) {
        String safeWindowId = windowId == null || windowId.isBlank()
                ? "unknown"
                : windowId.replaceAll("[^a-zA-Z0-9._-]", "_");
        Path directory = Path.of("images", "temp", safeWindowId).toAbsolutePath().normalize();
        Path rawPath = directory.resolve("team_role_tooltip_raw.png");
        Path maskPath = directory.resolve("team_role_tooltip_mask.png");
        try {
            Files.createDirectories(directory);
            boolean rawWritten = ImageIO.write(raw, "png", rawPath.toFile());
            byte[] maskBytes = Base64.getDecoder().decode(payload.base64());
            Files.write(maskPath, maskBytes);
            log.info("local team-role tooltip evidence saved: windowId={} raw={} mask={} "
                            + "groupHash={} rawWritten={} maskBytes={}",
                    windowId, rawPath, maskPath, payload.hash(), rawWritten, maskBytes.length);
        } catch (IOException | IllegalArgumentException failure) {
            log.warn("local team-role tooltip evidence save failed: windowId={} raw={} mask={} reason={}",
                    windowId, rawPath, maskPath, failure.getMessage(), failure);
        }
    }

    private BufferedImage hoverAndCapture(WindowRuntimeContext context, BooleanSupplier cancelled) {
        if (cancelled.getAsBoolean()) {
            return null;
        }
        WindowNativeBinding binding = bindingRefreshService.refreshAndCommit(context).orElse(null);
        if (binding == null || !binding.hasNativeHandle() || !binding.hasGeometry()) {
            return null;
        }
        BufferedImage[] captured = new BufferedImage[1];
        int hoverX = binding.getX() + HOVER_X
                + ThreadLocalRandom.current().nextInt(-HOVER_RADIUS_X, HOVER_RADIUS_X + 1);
        int hoverY = binding.getY() + HOVER_Y
                + ThreadLocalRandom.current().nextInt(-HOVER_RADIUS_Y, HOVER_RADIUS_Y + 1);
        boolean completed = inputSequences.submitFrozenExactWindowExclusiveAndWait(
                "team-role:cr212:hover-capture:" + context.getWindowId(), context, binding, () -> {
                    if (cancelled.getAsBoolean()) {
                        return false;
                    }
                    inputProvider.moveMouse(hoverX, hoverY);
                    if (!sleep(HOVER_SETTLE_MS, cancelled)) {
                        return false;
                    }
                    if (cancelled.getAsBoolean()) {
                        return false;
                    }
                    captured[0] = capture(binding, TOOLTIP_X, TOOLTIP_Y, TOOLTIP_W, TOOLTIP_H);
                    return captured[0] != null;
                }).isCompleted();
        return completed ? captured[0] : null;
    }

    private BufferedImage capture(WindowNativeBinding binding, int x, int y, int width, int height) {
        return captureService.captureRegion(binding, binding.getX(), binding.getY(),
                        binding.getX() + x, binding.getY() + y,
                        binding.getX() + x + width, binding.getY() + y + height)
                .map(BoundWindowCaptureService.CaptureResult::image)
                .orElse(null);
    }

    private static boolean sleep(long millis, BooleanSupplier cancelled) {
        long deadline = System.nanoTime() + java.time.Duration.ofMillis(millis).toNanos();
        while (!cancelled.getAsBoolean()) {
            long remainingMs = Math.max(0L,
                    java.time.Duration.ofNanos(deadline - System.nanoTime()).toMillis());
            if (remainingMs <= 0L) {
                return true;
            }
            try {
                Thread.sleep(Math.min(50L, remainingMs));
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt();
                return false;
            }
        }
        return false;
    }

    private static boolean looksLikeTooltip(BufferedImage image) {
        int white = 0;
        int purple = 0;
        int rows = 0;
        int transitions = 0;
        int maxRow = 0;
        int[] columns = new int[image.getWidth()];
        for (int y = 0; y < image.getHeight(); y++) {
            int row = 0;
            boolean previous = false;
            for (int x = 0; x < image.getWidth(); x++) {
                int rgb = image.getRGB(x, y);
                boolean text = isWhite(rgb) || isPurple(rgb);
                if (isWhite(rgb)) white++;
                if (isPurple(rgb)) purple++;
                if (text) {
                    row++;
                    columns[x]++;
                }
                if (text && !previous) transitions++;
                previous = text;
            }
            if (row >= 2) rows++;
            maxRow = Math.max(maxRow, row);
        }
        int usedColumns = 0;
        for (int count : columns) if (count > 0) usedColumns++;
        return white >= WHITE_MIN && purple >= PURPLE_MIN && rows >= 8
                && usedColumns >= 20 && transitions >= 20
                && maxRow <= Math.max(1, image.getWidth() * 80 / 100);
    }

    private static MaskPayload mask(BufferedImage raw) {
        BufferedImage mask = new BufferedImage(raw.getWidth(), raw.getHeight(), BufferedImage.TYPE_BYTE_BINARY);
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            for (int y = 0; y < raw.getHeight(); y++) {
                for (int x = 0; x < raw.getWidth(); x++) {
                    mask.setRGB(x, y, isTooltipSignaturePixel(raw.getRGB(x, y)) ? 0xFFFFFF : 0x000000);
                }
            }
            if (!ImageIO.write(mask, "png", output)) {
                return null;
            }
            byte[] png = output.toByteArray();
            return new MaskPayload("mask-" + sha256(png), Base64.getEncoder().encodeToString(png));
        } catch (IOException failure) {
            log.warn("local team-role mask encode failed", failure);
            return null;
        } finally {
            mask.flush();
        }
    }

    private static String sha256(byte[] bytes) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
        } catch (NoSuchAlgorithmException unavailable) {
            throw new IllegalStateException("SHA-256 unavailable", unavailable);
        }
    }

    static String rawArgbSha256(BufferedImage image) {
        ByteBuffer pixels = ByteBuffer.allocate(image.getWidth() * image.getHeight() * Integer.BYTES);
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                pixels.putInt(image.getRGB(x, y));
            }
        }
        return sha256(pixels.array());
    }

    static boolean isTooltipSignaturePixel(int rgb) {
        int r = (rgb >> 16) & 0xff;
        int g = (rgb >> 8) & 0xff;
        int b = rgb & 0xff;
        boolean whiteText = r >= 155 && g >= 155 && b >= 155;
        boolean greenText = g >= 105 && g - r >= 18 && g - b >= 18;
        boolean purpleText = r >= 95 && b >= 105 && r - g >= 18 && b - g >= 18;
        boolean yellowText = r >= 125 && g >= 95 && b <= 125 && r - b >= 25 && g - b >= 15;
        return whiteText || greenText || purpleText || yellowText;
    }

    private static boolean isWhite(int rgb) {
        return ((rgb >> 16) & 255) >= 210 && ((rgb >> 8) & 255) >= 210 && (rgb & 255) >= 210;
    }

    private static boolean isPurple(int rgb) {
        int r = (rgb >> 16) & 255;
        int g = (rgb >> 8) & 255;
        int b = rgb & 255;
        return r >= 120 && b >= 140 && g <= 120 && b > g + 40;
    }

    public enum Role { SOLO, UNKNOWN }

    public record Preflight(String windowId, Role role, String groupHash, boolean representative, String maskBase64) {
        static Preflight completed(String windowId, Role role, String groupHash, boolean representative,
                                  String maskBase64) {
            return new Preflight(windowId, role, groupHash, representative, maskBase64);
        }
    }

    private record Candidate(WindowRuntimeContext context, String windowId, String anchorHash) {
        static Candidate of(WindowRuntimeContext context, String anchorHash) {
            return new Candidate(context, context.getWindowId(), anchorHash);
        }
    }

    private record TooltipCandidate(Candidate candidate, MaskPayload payload) { }

    private record TooltipResolution(TooltipCandidate representative, boolean captureSucceeded) { }

    private record TooltipInspection(MaskPayload payload, boolean captureSucceeded) { }

    private record MaskPayload(String hash, String base64) { }
}
