package com.bot.dhxy.service.dialog;

public enum DialogOperation {
    INSPECT,
    GIVE_ITEM_IF_AVAILABLE,
    CLICK_KEYWORD,
    CLICK_REMEMBERED_OPTION,
    VERIFY_EXPECTED_DIALOG,
    CLICK_BUSINESS_OPTION,
    CLICK_GREEN_TEMPLATE,
    WUHUAN_SHOE_SHOP_BUY_OPTION,
    VERIFY_WHITE_TEMPLATE,
    ROUTE_TRANSFER,
    READ_STORY_OBJECTIVE,
    ACCEPT_TASK,
    CLEANUP
}
