package com.bot.dhxy.service.dialog;

public enum DialogOptionPolicy {
    IGNORE,
    VERIFY_OPTION,
    CLICK_KEYWORD,
    CLICK_REMEMBERED_POINT,
    CLICK_BUSINESS_OPTION,
    CLICK_GREEN_TEMPLATE,
    VERIFY_GREEN_TEMPLATE,
    GIVE_ITEM_IF_AVAILABLE,
    FALLBACK_FIRST_OPTION,
    FALLBACK_LAST_OPTION
}
