package com.bot.dhxy.service.dialog;

public enum DialogHandleResult {
    NO_DIALOG,
    STORY_IGNORED,
    STORY_CLICKED,
    OPTION_IGNORED,
    OPTION_KEYWORD_CLICKED,
    OPTION_KEYWORD_NOT_FOUND,
    BUSINESS_OPTION_CLICKED,
    BUSINESS_OPTION_NOT_FOUND,
    GIVE_ITEM_DONE,
    GIVE_OPTION_NOT_FOUND,
    GIVE_ITEM_FAILED,
    FALLBACK_CLICKED,
    INTERRUPTED,
    FAILED
}
